### ISSUE TITLE
Interlace Error , Exception: No target provided, or empty target list

### ISSUE THREAD

**Issue by violinist2149** [Dheerajmadhukar/karma_v2#26]
I am getting the below error while executing karma_v2 : 

Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.8', 'console_scripts', 'interlace')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Interlace-1.9.8-py3.11.egg/Interlace/interlace.py", line 34, in main
  File "/usr/local/lib/python3.11/dist-packages/Interlace-1.9.8-py3.11.egg/Interlace/lib/threader.py", line 112, in __init__
  File "/usr/local/lib/python3.11/dist-packages/Interlace-1.9.8-py3.11.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
  File "/usr/local/lib/python3.11/dist-packages/Interlace-1.9.8-py3.11.egg/Interlace/lib/core/input.py", line 271, in process_data_for_tasks_iterator
Exception: No target provided, or empty target list

I tried reinstalling Interlace , but no luck . I am running karma_v2 on Kali Linux .

**Comment by violinist2149** [comment]
Thanks !

**Comment by LowLevelJody** [comment]
is it fix? i have the same error. how to fix it?
